ViewComponents/CategoryViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ecommercestorewithaspcoremvc.DataAccess;
using ecommercestorewithaspcoremvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace ecommercestorewithaspcoremvc.ViewComponents
{
    [ViewComponent(Name ="Category")]
    public class CategoryViewComponent : ViewComponent
    {
        private readonly EcommerceContext _db;

        public CategoryViewComponent(EcommerceContext db)
        {
            this._db = db;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Category> categories = _db.Categories.Where(c => c.Status && c.parent == null).ToList();
            return View("Index", categories);
        }
    }
}

ViewComponents/SearchViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ecommercestorewithaspcoremvc.DataAccess;
using ecommercestorewithaspcoremvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace ecommercestorewithaspcoremvc.ViewComponents
{
    [ViewComponent(Name ="Search")]
    public class SearchViewComponent : ViewComponent
    {
        private readonly EcommerceContext _db;

        public SearchViewComponent(EcommerceContext db)
        {
            this._db = db;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Category> categories = _db.Categories.Where(c => c.Status && c.parent == null).ToList();
            return View("Index", categories);
        }
    }
}

ViewComponents/SlideShowViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ecommercestorewithaspcoremvc.DataAccess;
using ecommercestorewithaspcoremvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace ecommercestorewithaspcoremvc.ViewComponents
{
    [ViewComponent(Name ="SlideShow")]
    public class SlideShowViewComponent : ViewComponent
    {
        private readonly EcommerceContext _db;

        public SlideShowViewComponent(EcommerceContext db)
        {
            this._db = db;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<SlideShow> slideShow = _db.SlideShows.Where(c => c.Status).ToList();
            return View("Index", slideShow);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcommerceStoreWithASPCoreMVC</title>
    <link rel="stylesheet" href="~/Identity/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Identity/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light navbar-toggleable-sm bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="~/">EcommerceStoreWithASPCoreMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @{
                        var result = Engine.FindView(ViewContext, "_LoginPartial", isMainPage: false);
                    }
                    @if (result.Success)
                    {
                        await Html.RenderPartialAsync("_LoginPartial");
                    }
                    else
                    {
                        throw new InvalidOperationException("The default Identity UI layout requires a partial view '_LoginPartial' " +
                            "usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work. Based on your configuration " +
                            $"we have looked at it in the following locations: {System.Environment.NewLine}{string.Join(System.Environment.NewLine, result.SearchedLocations)}.");
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer border-top text-muted">
        <div class="container">
            &copy; 2022 - EcommerceStoreWithASPCoreMVC - <a asp-area="" asp-page="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/Identity/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Identity/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Identity/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootshop online Shopping cart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
	
	<!-- Bootstrap style --> 
    <link id="callCss" rel="stylesheet" href="~/user/themes/bootshop/bootstrap.min.css" media="screen"/>
    <link href="~/user/themes/css/base.css" rel="stylesheet" media="screen"/>
	<!-- Bootstrap style responsive -->	
	<link href="~/user/themes/css/bootstrap-responsive.min.css" rel="stylesheet"/>
	<link href="~/user/themes/css/font-awesome.css" rel="stylesheet" type="text/css">
	<!-- Google-code-prettify -->	
	<link href="themes/js/google-code-prettify/prettify.css" rel="stylesheet"/>
	<!-- fav and touch icons -->
    <link rel="shortcut icon" href="~/user/themes/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/user/themes/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/user/themes/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/user/themes/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/user/themes/images/ico/apple-touch-icon-57-precomposed.png">
	<style type="text/css" id="enject"></style>
  </head>
<body>
    <!-- Header -->
    <div id="header">
        <div class="container">
            <div id="welcomeLine" class="row">
                <div class="span6">Welcome!<strong> User</strong></div>
                <div class="span6">
                <div class="pull-right">
                    <a href="product_summary.html"><span class="">Fr</span></a>
                    <a href="product_summary.html"><span class="">Es</span></a>
                    <span class="btn btn-mini">En</span>
                    <a href="product_summary.html"><span>&pound;</span></a>
                    <span class="btn btn-mini">$155.00</span>
                    <a href="product_summary.html"><span class="">$</span></a>
                    <a href="product_summary.html"><span class="btn btn-mini btn-primary"><i class="icon-shopping-cart icon-white"></i> [ 3 ] Itemes in your cart </span> </a> 
                </div>
                </div>
            </div>
            <!-- Navbar -->
            <div id="logoArea" class="navbar">
                <a id="smallScreen" data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-inner">
                    <a class="brand" href="index.html"><img src="~/user/themes/images/logo.png" alt="Bootsshop"/></a>
                    
                    @await Component.InvokeAsync("Search")
                    
                    <ul id="topMenu" class="nav pull-right">
                        <li class=""><a href="special_offer.html">Specials Offer</a></li>
                        <li class=""><a href="normal.html">Delivery</a></li>
                        <li class=""><a href="contact.html">Contact</a></li>
                        <li class="">
                            <a href="#login" role="button" data-toggle="modal" style="padding-right:0"><span class="btn btn-large btn-success">Login</span></a>
                            <div id="login" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="login" aria-hidden="false" >
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h3>Login Block</h3>
                                </div>
                                <div class="modal-body">
                                    <form class="form-horizontal loginFrm">
                                    <div class="control-group">								
                                        <input type="text" id="inputEmail" placeholder="Email">
                                    </div>
                                    <div class="control-group">
                                        <input type="password" id="inputPassword" placeholder="Password">
                                    </div>
                                    <div class="control-group">
                                        <label class="checkbox">
                                        <input type="checkbox"> Remember me
                                        </label>
                                    </div>
                                    </form>		
                                    <button type="submit" class="btn btn-success">Sign in</button>
                                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
    
    @await Component.InvokeAsync("SlideShow")

    <!-- Main body -->
    <div id="mainBody">
        <div class="container">
            <div class="row">
                <!-- Sidebar -->
                <div id="sidebar" class="span3">
                    <div class="well well-small">
                        <a id="myCart" href="product_summary.html">
                            <img src="~/user/themes/images/ico-cart.png" alt="cart">3 Items in your cart  <span class="badge badge-warning pull-right">$155.00</span>
                        </a>
                    </div>
                    
                    @await Component.InvokeAsync("Category")
                    <br/>
                    <div class="thumbnail">
                        <img src="~/user/themes/images/products/panasonic.jpg" alt="Bootshop panasonoc New camera"/>
                        <div class="caption">
                            <h5>Panasonic</h5>
                            <h4 style="text-align:center">
                                <a class="btn" href="product_details.html"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">$222.00</a>
                            </h4>
                        </div>
                    </div>
                    <br/>
                    <div class="thumbnail">
                        <img src="~/user/themes/images/products/kindle.png" title="Bootshop New Kindel" alt="Bootshop Kindel">
                        <div class="caption">
                            <h5>Kindle</h5>
                            <h4 style="text-align:center"><a class="btn" href="product_details.html"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">$222.00</a></h4>
                        </div>
                    </div>
                    <br/>
                    <div class="thumbnail">
                        <img src="~/user/themes/images/payment_methods.png" title="Bootshop Payment Methods" alt="Payments Methods">
                        <div class="caption">
                            <h5>Payment Methods</h5>
                        </div>
                    </div>
                </div>
                <!-- Sidebar end -->
                <div class="span9">	
                    @RenderBody()	
                </div>
            </div>
        </div>
    </div>
    <!-- End main -->
	<!-- Footer -->
	<div  id="footerSection">
        <div class="container">
            <div class="row">
                <div class="span3">
                    <h5>ACCOUNT</h5>
                    <a href="login.html">YOUR ACCOUNT</a>
                    <a href="login.html">PERSONAL INFORMATION</a> 
                    <a href="login.html">ADDRESSES</a> 
                    <a href="login.html">DISCOUNT</a>  
                    <a href="login.html">ORDER HISTORY</a>
                </div>
                <div class="span3">
                    <h5>INFORMATION</h5>
                    <a href="contact.html">CONTACT</a>  
                    <a href="register.html">REGISTRATION</a>  
                    <a href="legal_notice.html">LEGAL NOTICE</a>  
                    <a href="tac.html">TERMS AND CONDITIONS</a> 
                    <a href="faq.html">FAQ</a>
                </div>
                <div class="span3">
                    <h5>OUR OFFERS</h5>
                    <a href="#">NEW PRODUCTS</a> 
                    <a href="#">TOP SELLERS</a>  
                    <a href="special_offer.html">SPECIAL OFFERS</a>  
                    <a href="#">MANUFACTURERS</a> 
                    <a href="#">SUPPLIERS</a> 
                </div>
                <div id="socialMedia" class="span3 pull-right">
                    <h5>SOCIAL MEDIA </h5>
                    <a href="#"><img width="60" height="60" src="~/user/themes/images/facebook.png" title="facebook" alt="facebook"/></a>
                    <a href="#"><img width="60" height="60" src="~/user/themes/images/twitter.png" title="twitter" alt="twitter"/></a>
                    <a href="#"><img width="60" height="60" src="~/user/themes/images/youtube.png" title="youtube" alt="youtube"/></a>
                </div> 
            </div>
            <p class="pull-right">&copy; Bootshop</p>
        </div>
        <!-- Container End -->
	</div>
    <!-- End footer -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="~/user/themes/js/jquery.js" type="text/javascript"></script>
	<script src="~/user/themes/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="~/user/themes/js/google-code-prettify/prettify.js"></script>
	
	<script src="~/user/themes/js/bootshop.js"></script>
    <script src="~/user/themes/js/jquery.lightbox-0.5.js"></script>
	
	<span id="themesBtn"></span>
</body>
</html>